<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Portal.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Portal.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Services.Portal\Mandate.Portal.csproj" />
	</ItemGroup>
	
</Project>
