<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Client.Http</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Client.Http</RootNamespace>
		<PackageId>KPMG.Pulse.Back.Accounting.Mandate.Client.Http</PackageId>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Implementation of proxy client to Constellation Mandate API</Description>
		<PackageProjectUrl>https://dev.azure.com/kpmgfr/Constellation/</PackageProjectUrl>
		<RepositoryUrl>https://dev.azure.com/kpmgfr/Constellation/_git/KPMG.Pulse.Back.Accounting.Mandate</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReleaseNotes>1.0.0 - Initial version</PackageReleaseNotes>
		<SignAssembly>false</SignAssembly>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Kpmg.Constellation.Net.Http" Version="1.73.4-develop" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Client\Mandate.Client.csproj" />
	</ItemGroup>

</Project>
