<!-- 
	MSBuild files for all the Mandate projects which contains common properties
-->

<Project>

	<!-- Common properties for all projects -->
	<PropertyGroup>
		<Authors>KPMG</Authors>
		<Company>KPMG</Company>
		<Copyright>Copyright (C) 2023 KPMG</Copyright>
		<Product>KPMG Pulse</Product>
	</PropertyGroup>

	<!-- Common C# analyzers files -->
	<ItemGroup>
		<AdditionalFiles Include="..\..\stylecop.json" Link="stylecop.json" />
		<None Include="..\..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>
</Project>