<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Notifications</AssemblyName>
    <RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Kpmg.AspNetCore.Authentication.ConstellationIdentityService" Version="1.1.0.10" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
	<PackageReference Include="Pulse.Back.Notifications.Commons" Version="1.0.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Mandate.Application.csproj" />
    <ProjectReference Include="..\Services.Portal\Mandate.Portal.csproj" />
  </ItemGroup>
</Project>
