<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Notifications</AssemblyName>
    <RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
	<PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
	<PackageReference Include="Pulse.Back.Notifications.Commons" Version="1.0.0.4" />
	<PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
	<PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Mandate.Application.csproj" />
  </ItemGroup>
</Project>
