<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Client.Http.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Client.Http.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Client.Http\Mandate.Client.Http.csproj" />
	</ItemGroup>

</Project>
