<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Client.Http.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Client.Http.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Net.Http" Version="4.3.4" />
	  <PackageReference Include="System.Text.Json" Version="8.0.5" />
	  <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Client.Http\Mandate.Client.Http.csproj" />
	</ItemGroup>

</Project>
