<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.JeDeclare.Client.Http</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.JeDeclare.Client.Http</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Kpmg.Constellation.Net.Http" Version="1.2.1.2" />
	  <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Services.JeDeclare.Client\Mandate.JeDeclare.Client.csproj" />
	</ItemGroup>

</Project>
