<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Sql</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Sql</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
	</ItemGroup>

</Project>
