<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.AspNetCore.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.AspNetCore.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.IO.Packaging" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Mandate.Messaging\Mandate.Messaging.csproj" />
		<ProjectReference Include="..\Services.Sql.Implementation\Mandate.Sql.Implementation.Tests.csproj" />
		<ProjectReference Include="..\Tools\Mandate.Tools.Tests.csproj" />
		<ProjectReference Include="..\..\src\Api\Mandate.AspNetCore.csproj" />
	</ItemGroup>

</Project>
