<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Client.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Client.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tools\Mandate.Tools.Tests.csproj" />
		<ProjectReference Include="..\..\src\Client\Mandate.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\Queries\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
	  <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>

</Project>
