<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Adapters</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Adapters</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Entities\Mandate.csproj" />
		<ProjectReference Include="..\Services.JeDeclare.Client\Mandate.JeDeclare.Client.csproj" />
		<ProjectReference Include="..\Services.Mongo\Mandate.Mongo.csproj" />
		<ProjectReference Include="..\Services.Sql\Mandate.Sql.csproj" />
	</ItemGroup>

</Project>
