trigger: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/pull-request/back.yaml@Pulse
  parameters:
    srcPath: 01_API/src/Api/Mandate.AspNetCore.csproj
    testsPath: 01_API/tests/**/*.csproj
    name: mandate
    dotnetVersion: 10.x