trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: true
- name: deployToItg
  displayName: 'Déployer sur ITG'
  type: boolean
  default: false


resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/quick-build/back.yaml@Pulse
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    deployToItg: ${{ parameters.deployToItg }}
    srcPath: 02_MandateFunction/src/Mandate.AzureFunctions/KPMG.Pulse.Back.Accounting.Mandate.Function.csproj
    domain: mdt
    name: 'mdtFunction'
    appType: functionApp
    id: '02'