<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Application</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Arial.ttf">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Aspose.Total.lic">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspose.PDF" Version="24.6.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
		<PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Entities\Mandate.csproj" />
	</ItemGroup>

</Project>
