<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Application.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Application.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Adapters\Mandate.Adapters.csproj" />
		<ProjectReference Include="..\..\src\Services.Sql.Implementation\Mandate.Sql.Implementation.csproj" />
		<ProjectReference Include="..\Services.Sql.Implementation\Mandate.Sql.Implementation.Tests.csproj" />
		<ProjectReference Include="..\Tools\Mandate.Tools.Tests.csproj" />
		<ProjectReference Include="..\..\src\Application\Mandate.Application.csproj" />
	</ItemGroup>

</Project>
