<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Asn1" Version="10.0.11" />
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mandate.Messaging\Mandate.Messaging.csproj" />
  </ItemGroup>

</Project>
