<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Portal</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Portal</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="KPMG.Constellation.Portal.Client.Http" Version="1.63.13-develop" />
	</ItemGroup>
	
</Project>
