<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Portal</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Portal</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Kpmg.AspNetCore.Authentication.ConstellationIdentityService" Version="1.1.0.3" />
		<PackageReference Include="KPMG.Constellation.Portal.Client.Http" Version="1.63.13-develop" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
	</ItemGroup>
</Project>
