<!-- 
	MSBuild files for all the Mandate unit tests projects which contains common properties
-->

<Project>
	<!-- Include the parent 'Directory.Build.props' file -->
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

	<!-- Common NuGet packages for all unit tests projects -->
	<ItemGroup>
		<PackageReference Include="AutoFixture" Version="4.18.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
		<PackageReference Include="xunit" Version="2.5.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" Version="6.12.0" />
		<PackageReference Include="FluentAssertions.Json" Version="6.1.0" />
		<PackageReference Include="Moq" Version="4.18.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="coverlet.collector" Version="6.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<Using Include="System.Text" />
		<Using Include="System.Xml" />
		<Using Include="System.Xml.Serialization" />
		<Using Include="FluentAssertions" />
		<Using Include="Moq" />
		<Using Include="Xunit" />
	</ItemGroup>
</Project>