<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.JeDeclare.Client</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.JeDeclare.Client</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Kpmg.Constellation.Net.Http" Version="1.59.1-develop" />
	  <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
	</ItemGroup>
	
</Project>
