<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>KPMG.Pulse.Back.Accounting.Mandate.Adapters.Tests</AssemblyName>
		<RootNamespace>KPMG.Pulse.Back.Accounting.Mandate.Adapters.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\PortalApi\PortalApi.csproj" />
		<ProjectReference Include="..\..\src\Services.Formio.Client.Http\Mandate.Formio.Client.Http.csproj" />
		<ProjectReference Include="..\..\src\Services.Formio.Client\Mandate.Formio.Client.csproj" />
		<ProjectReference Include="..\Tools\Mandate.Tools.Tests.csproj" />
		<ProjectReference Include="..\..\src\Services.JeDeclare.Client.Http\Mandate.JeDeclare.Client.Http.csproj" />
		<ProjectReference Include="..\..\src\Services.Mongo.Implementation\Mandate.Mongo.Implementation.csproj" />
		<ProjectReference Include="..\..\src\Services.Sql.Implementation\Mandate.Sql.Implementation.csproj" />
		<ProjectReference Include="..\..\src\Adapters\Mandate.Adapters.csproj" />
		<ProjectReference Include="..\Services.Sql.Implementation\Mandate.Sql.Implementation.Tests.csproj" />
	</ItemGroup>

</Project>
