trigger: none
pool:
  vmImage: windows-latest

parameters:
- name: devIndex
  displayName: 'Index de l environnement cible (seulement pour un déploiement sur env de DEV)'
  type: number
  default: 0
- name: deployType
  displayName: "Technical parameter : don t modify it !"
  type: string
  default: 'standard'

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.ConstellationDevOps'
    type: git
    ref: 'refs/heads/Release/v2.0'

extends:
  template: pipelines/templates/platform.back.api.yaml@Pulse
  parameters:
    devIndex: ${{ parameters.devIndex }}
    deployType: ${{ parameters.deployType }}
    sonarExclusions: '**/Program.cs'
    layer: Domain
    domain: mdt
    resource:
      id: '02'
      name: 'mdtFunction'
      path: 02_MandateFunction\src\Mandate.AzureFunctions\KPMG.Pulse.Back.Accounting.Mandate.Function.csproj
      type: 'functionApp' 
      tests: |
          02_MandateFunction\tests\**\*.csproj
          01_API\tests\Services.Sql.Implementation\Mandate.Sql.Implementation.Tests.csproj
          01_API\tests\Services.Sql\Mandate.Sql.Tests.csproj
          01_API\tests\Adapters\Mandate.Adapters.Tests.csproj
          01_API\tests\Application\Mandate.Application.Tests.csproj
          01_API\tests\Client.Http\Mandate.Client.Http.Tests.csproj
          01_API\tests\Client\Mandate.Client.Tests.csproj
          01_API\tests\Services.JeDeclare.Client\Mandate.JeDeclare.Client.Tests.csproj
          01_API\tests\Services.JeDeclare.Client.Http\Mandate.JeDeclare.Client.Http.Tests.csproj
    dotnetcore: 8.x