name: Constellation.Proxy.Mandate

trigger:
  branches:
    include:
      - main
      - develop
      - release/*

  paths:
    include:
      - 01_API/src/Client/*
      - 01_API/src/Client.Http/*

pool:
  vmImage: 'windows-latest'

variables:
  Configuration: 'Release'
  Version: '0.1.1'
  Revision: $[counter(variables['Version'], 1)]

jobs:
- job: Build
  steps:

  - task: NuGetToolInstaller@1
    displayName: "Install NuGet"

  - task: PowerShell@2
    displayName: "Update assembly version"
    inputs:
      filePath: '01_API\build\Update-AssemblyVersion.ps1'
      arguments: '
      -Version $(Version)
      -Revision $(Revision)
      -Tag "$(Build.SourceBranchName)"
      -GitCommit "$(Build.SourceVersion)"'

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'MSBuild'
      projectKey: 'MyPulse_Back_Mandate'
      projectName: 'KPMG.Pulse.Back.Accounting.Mandate'
      extraProperties: |
        sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)\**\*.trx
        sonar.exclusions=**/Migrations/*.cs
        sonar.dotnet.excludeTestProjects=false
        sonar.issue.ignore.multicriteria=cs1
        sonar.issue.ignore.multicriteria.cs1.ruleKey=csharpsquid:S3900
        sonar.issue.ignore.multicriteria.cs1.resourceKey=**/*.cs

  - task: NuGetCommand@2
    displayName: "Restore NuGet packages"
    inputs:
      command: 'restore'
      restoreSolution: '01_API/Mandate.CleanArchi.sln'
      feedsToUse: 'config'
      nugetConfigPath: '$(build.sourcesdirectory)\01_API\NuGet.config'

  - task: VSBuild@1
    displayName: "Build the .NET Standard Mandate Client NuGet packages"
    inputs:
      solution: '01_API/src/Client.Http/Mandate.Client.Http.csproj'
      msbuildArgs: '
      /p:AssemblyVersion=$(Version)
      /p:AssemblyInformationalVersion=$(InformationalVersion)
      /p:OutputPath="$(Build.ArtifactStagingDirectory)\\Client.Http\\"'
      configuration: '$(Configuration)'

  - task: VSTest@2
    displayName: 'Run the unit tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*tests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runSettingsFile: 'CodeCoverage.runsettings'
      codeCoverageEnabled: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish NuGet Packages artifacts"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\\'
      ArtifactName: 'NuGet Packages'
      publishLocation: 'Container'

  - task: NuGetCommand@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/*/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '3eae4231-20cf-428b-9e83-aac06ad8acb0/c3b7c547-1a75-4ab9-9f80-e29d4b69d23f'
  
  - task: SonarQubeAnalyze@5
    condition: succeeded()

  - task: SonarQubePublish@5
    condition: succeeded()
    inputs:
      pollingTimeoutSec: '300'