name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - develop
    - release/*
  paths:
    include:
    - 01_API/src/Client.Http

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: CICD
      name: 'Industrialisation/Industrialisation'
      type: git
      ref: 'refs/heads/features/cicd_as_conf'
    - repository: Pulse
      name: 'Pulse.Operations.Pipelines'
      type: git
      ref: 'refs/heads/Release/v2.0' 

variables:
  - template: pipelines/variables/common.yaml@Pulse

extends:
  template: CICD/PipelineTemplate.yaml@CICD
  parameters:
    versioning:
      mode: legacy
      major: 1
    build:
      tooling:
        dotnetCore:
        - 8.x
        nuget:
          feed: '$(FeedPackageName)'
      sonarCloud:
        projectKey: Pulse_Package_Mandate.Client
        projectName: "(KPMG Pulse)[Package] Mandate.Client - mdt"
      steps:
      - type: nuget
        name: Mandate.Client.Http
        netcoreProjects: 01_API\src\Client.Http\Mandate.Client.Http.csproj
        nugetFeed: '$(FeedPackageName)' 
